-- Isolated test schema only. Never run this file in Supabase.
create role anon;
create role authenticated;
create schema auth;
create function auth.uid() returns uuid language sql stable as
$$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create table public.profiles(id uuid primary key, nickname text, role text);
insert into profiles values
 ('11111111-1111-1111-1111-111111111111','admin','admin'),
 ('22222222-2222-2222-2222-222222222222','user','user');
create table public.characters(
 id bigint generated by default as identity primary key, commu_profile_id uuid not null, name text not null,
 condition integer not null default 100, money bigint not null default 0,
 base_daily_actions integer not null default 5, active boolean not null default true,
 updated_at timestamptz not null default now()
);
create table public.stat_definitions(id bigint generated by default as identity (start with 1000) primary key,
 stat_key text not null unique, display_name text not null, description text,
 default_value integer not null default 0, enabled boolean not null default true, created_at timestamptz not null default now());
create table public.character_stats(
 id bigint generated by default as identity primary key,
 character_id bigint references characters, stat_id bigint references stat_definitions,
 value integer not null default 0, updated_at timestamptz not null default now(), unique(character_id,stat_id)
);
create table public.skills(id bigint generated by default as identity (start with 1000) primary key,
 name text not null, description text, enabled boolean default true, skill_key text not null unique);
create table public.character_skills(
 id bigint generated by default as identity primary key, character_id bigint references characters,
 skill_id bigint references skills, active boolean default true, unique(character_id,skill_id)
);
create table public.commands(
 id bigint generated by default as identity (start with 1000) primary key, command text not null unique,
 display_name text, description text, enabled boolean not null default true, hidden boolean not null default false,
 consumes_action boolean not null default true, dice_enabled boolean not null default false,
 dice_min integer not null default 1, dice_max integer not null default 100, dice_threshold integer,
 command_type text not null default 'action', status_fields jsonb not null default '[]',
 success_message text, fail_message text, created_at timestamptz not null default now()
);
create table public.skill_modifiers(
 id bigint generated by default as identity (start with 1000) primary key, skill_id bigint references skills, modifier_type text, value numeric,
 target_command_id bigint references commands, target_stat_id bigint references stat_definitions,
 period text, max_uses integer, params jsonb default '{}', enabled boolean default true, priority integer default 100
);
create table public.skill_usages(id bigint generated by default as identity primary key,
 character_id bigint, skill_modifier_id bigint, used_at timestamptz);
create table public.action_logs(id bigint generated by default as identity primary key,
 character_id bigint, action_consumed boolean, used_at timestamptz);
create table public.command_rules(
 id bigint generated by default as identity primary key, command_id bigint not null references commands,
 rule_key text not null, enabled boolean not null default true, priority integer not null default 100,
 use_from integer,use_to integer,previous_command_id bigint references commands,condition_min integer,condition_max integer,dice_outcome text,
 condition_delta integer not null default 0,money_delta bigint not null default 0,description text,created_at timestamptz not null default now(),
 money_min numeric,money_max numeric,rule_type text not null default 'effect',unique(command_id,rule_key)
);
create table public.command_rule_stat_effects(
 id bigint generated by default as identity primary key,rule_id bigint not null references command_rules,
 stat_id bigint not null references stat_definitions,delta integer not null,unique(rule_id,stat_id)
);
insert into characters(id,commu_profile_id,name,condition,money) values
 (1,'33333333-3333-3333-3333-333333333333','김철수',72,123456),
 (2,'44444444-4444-4444-4444-444444444444','다른 캐릭터',50,0);
insert into stat_definitions(id,stat_key,display_name,enabled) values (1,'work','업무성과',true),(2,'attendance','근태',true),(3,'new_stat','새 스탯',true);
insert into character_stats(character_id,stat_id,value) values (1,1,12),(1,2,-2);
insert into commands(id,command) values (1,'/청소');
insert into skills(id,name,description,enabled,skill_key) values (1,'요령','테스트 효과',true,'yoryeong'),(2,'비활성 정의','',false,'disabled'),(3,'신규 스킬','',true,'new_skill');
insert into character_skills(character_id,skill_id) values (1,1),(1,2),(2,1);
insert into skill_modifiers(id,skill_id,modifier_type,value,period,max_uses,target_command_id) values
 (1,1,'daily_action_bonus',1,null,null,null),
 (2,1,'dice_reroll',1,'day',1,null),
 (3,1,'block_negative_stat',0,'week',1,null),
 (4,1,'daily_action_bonus',99,null,null,1),
 (5,2,'daily_action_bonus',99,null,null,null),
 (6,1,'daily_action_bonus',99,'day',1,null),
 (7,1,'daily_action_bonus',99,null,null,null);
update skill_modifiers set enabled=false where id=7;
insert into action_logs(character_id,action_consumed,used_at)
select 1,true,(date_trunc('day',now() at time zone 'Asia/Seoul') at time zone 'Asia/Seoul') + interval '1 second'
from generate_series(1,3);
insert into action_logs(character_id,action_consumed,used_at) values
 (1,false,now()),
 (1,true,(date_trunc('day',now() at time zone 'Asia/Seoul') at time zone 'Asia/Seoul') - interval '1 microsecond'),
 (1,true,(date_trunc('day',now() at time zone 'Asia/Seoul') + interval '1 day') at time zone 'Asia/Seoul');
insert into skill_usages(character_id,skill_modifier_id,used_at) values
 (1,2,now()), (1,6,now()),
 (1,3,(date_trunc('week',now() at time zone 'Asia/Seoul') at time zone 'Asia/Seoul') - interval '1 microsecond');
