-- Additive community schema; existing PRESS/RESOURCE objects are untouched.
begin;
create schema if not exists private;

create table public.community_posts (
  id bigint generated by default as identity primary key,
  board_type text not null check (board_type in ('anonymous','stock')),
  author_id uuid not null references public.profiles(id),
  title varchar(200) not null check (char_length(btrim(title)) between 1 and 200),
  content text not null check (char_length(btrim(content)) between 1 and 20000),
  view_count integer not null default 0 check (view_count >= 0),
  comment_count integer not null default 0 check (comment_count >= 0),
  created_at timestamptz not null default now(),
  edited_at timestamptz
);
create index community_posts_feed_idx on public.community_posts(board_type,created_at desc,id desc);
create index community_posts_author_idx on public.community_posts(author_id);
create table public.community_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.community_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id),
  content text not null check (char_length(btrim(content)) between 1 and 2000),
  created_at timestamptz not null default now(),
  edited_at timestamptz
);
create index community_comments_thread_idx on public.community_comments(post_id,created_at,id);
create index community_comments_user_idx on public.community_comments(user_id);
create table public.stock_profiles (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  nickname varchar(20) not null check (nickname = btrim(nickname) and char_length(nickname) between 1 and 20),
  bio varchar(100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index stock_profiles_nickname_unique on public.stock_profiles(lower(nickname));
alter table public.community_posts enable row level security;
alter table public.community_comments enable row level security;
alter table public.stock_profiles enable row level security;

create policy community_posts_read on public.community_posts for select to authenticated using (true);
create policy community_posts_create on public.community_posts for insert to authenticated with check (author_id = (select auth.uid()) and (board_type = 'anonymous' or exists (select 1 from public.stock_profiles where user_id = (select auth.uid()))));
create policy community_posts_edit on public.community_posts for update to authenticated using (author_id = (select auth.uid())) with check (author_id = (select auth.uid()));
create policy community_posts_delete on public.community_posts for delete to authenticated using (author_id = (select auth.uid()) or (select public.is_admin()));
create policy community_comments_read on public.community_comments for select to authenticated using (true);
create policy community_comments_create on public.community_comments for insert to authenticated with check (user_id = (select auth.uid()) and exists (select 1 from public.community_posts p where p.id = post_id and (p.board_type = 'anonymous' or exists (select 1 from public.stock_profiles where user_id = (select auth.uid())))));
create policy community_comments_edit on public.community_comments for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy community_comments_delete on public.community_comments for delete to authenticated using (user_id = (select auth.uid()) or (select public.is_admin()));
create policy stock_profiles_read on public.stock_profiles for select to authenticated using (true);
create policy stock_profiles_create on public.stock_profiles for insert to authenticated with check (user_id = (select auth.uid()));
create policy stock_profiles_edit on public.stock_profiles for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

-- Column grants also prevent owners from forging counters, dates or board/ownership.
revoke all on public.community_posts,public.community_comments,public.stock_profiles from public,anon,authenticated;
grant select,delete on public.community_posts,public.community_comments to authenticated;
grant select on public.stock_profiles to authenticated;
grant insert(board_type,author_id,title,content),update(title,content) on public.community_posts to authenticated;
grant insert(post_id,user_id,content),update(content) on public.community_comments to authenticated;
grant insert(user_id,nickname,bio),update(nickname,bio) on public.stock_profiles to authenticated;
revoke all on sequence public.community_posts_id_seq,public.community_comments_id_seq from public,anon,authenticated;
grant usage on sequence public.community_posts_id_seq,public.community_comments_id_seq to authenticated;

create function private.community_content_edited() returns trigger language plpgsql set search_path = '' as $$
begin
  if new.content is distinct from old.content or (to_jsonb(new)->>'title') is distinct from (to_jsonb(old)->>'title') then
    new.edited_at := now();
  end if;
  return new;
end;
$$;
create trigger community_posts_edited before update on public.community_posts for each row execute function private.community_content_edited();
create trigger community_comments_edited before update on public.community_comments for each row execute function private.community_content_edited();
create function private.community_comment_counter() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    update public.community_posts set comment_count = comment_count + 1 where id = new.post_id;
    return new;
  end if;
  update public.community_posts set comment_count = greatest(0,comment_count - 1) where id = old.post_id;
  return old;
end;
$$;
create trigger community_comments_count after insert or delete on public.community_comments for each row execute function private.community_comment_counter();
create function private.stock_profile_timestamp() returns trigger language plpgsql set search_path = '' as $$
begin new.updated_at := now(); return new; end;
$$;
create trigger stock_profiles_updated before update on public.stock_profiles for each row execute function private.stock_profile_timestamp();
revoke all on function private.community_content_edited(),private.community_comment_counter(),private.stock_profile_timestamp() from public,anon,authenticated;

create function public.increment_community_post_view(p_post_id bigint) returns integer language plpgsql security definer set search_path = '' as $$
declare result integer;
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  update public.community_posts set view_count = view_count + 1 where id = p_post_id returning view_count into result;
  return result;
end;
$$;
revoke all on function public.increment_community_post_view(bigint) from public,anon,authenticated;
grant execute on function public.increment_community_post_view(bigint) to authenticated;
commit;
